### ISSUE TITLE
Nextcloud 15

### ISSUE THREAD

**Issue by Aviorleking** [mwalbeck/nextcloud-breeze-dark#42]
Hi I'm actually on nextcloud 15 and your theme work pretty well on it
but there is some tweaks to add to make it perfect
examples:

actionbar
![image](https://user-images.githubusercontent.com/15822031/49736709-223ee100-fc8b-11e8-9bec-5cf9db26290f.png)
can be corrected by setting
```css
#controls {
    background-color: transparent;
}
```
result:
![image](https://user-images.githubusercontent.com/15822031/49736824-734ed500-fc8b-11e8-8977-899b90545307.png)

---

appbar on hover
![image](https://user-images.githubusercontent.com/15822031/49736796-5f0ad800-fc8b-11e8-8637-bae792e0b536.png)
can be corrected by removing this

(I actually don't know if it's wanted or not)
```css
#appmenu li span { /*around line 1620*/
    border: 1px solid #706f6e;
}
```
to result to 
![image](https://user-images.githubusercontent.com/15822031/49736883-a2654680-fc8b-11e8-965a-4ff5bac292c3.png)

---

finally
![image](https://user-images.githubusercontent.com/15822031/49737130-51a21d80-fc8c-11e8-959b-31054a5a1a8d.png)
can be corrected by adding
```css
#appmenu:hover li:hover span {
    background-color: transparent;
}
```
![image](https://user-images.githubusercontent.com/15822031/49737337-e9a00700-fc8c-11e8-9329-755abdd82332.png)

and that's pretty much all a saw
